export enum StatusBadgeEnum {
  BLUE = "BLUE",
  RED = "RED",
  GREEN = "GREEN",
  GRAY = "GRAY",
  SAFFRON = "SAFFRON",
  PLUM = "PLUM",
}

export const DEFAULT_STATUS_BADGE_MAP: Record<string, StatusBadgeEnum> = {
  not_found: StatusBadgeEnum.GRAY,
  draft: StatusBadgeEnum.SAFFRON,
  premarket: StatusBadgeEnum.BLUE,
  in_use: StatusBadgeEnum.GREEN,
  archived: StatusBadgeEnum.GRAY,
  retracted: StatusBadgeEnum.GRAY,
  inactive: StatusBadgeEnum.GRAY,
  expired: StatusBadgeEnum.RED,
  discontinued: StatusBadgeEnum.GRAY,
  active: StatusBadgeEnum.GREEN,
  transferred: StatusBadgeEnum.GRAY,
  published: StatusBadgeEnum.GREEN,
  in_progress: StatusBadgeEnum.SAFFRON,
  processing: StatusBadgeEnum.SAFFRON,
  complete: StatusBadgeEnum.GREEN,
  file_uploaded: StatusBadgeEnum.BLUE,
  pre_processing: StatusBadgeEnum.SAFFRON,
  pending: StatusBadgeEnum.SAFFRON,
  error: StatusBadgeEnum.RED,
  edit_in_progress: StatusBadgeEnum.SAFFRON,
  pending_approval: StatusBadgeEnum.SAFFRON,
  missing_data: StatusBadgeEnum.RED,
  ready_to_publish: StatusBadgeEnum.BLUE,
  transfer_pending: StatusBadgeEnum.SAFFRON,
};
